# This file was generated by GoReleaser. DO NOT EDIT.
cask "a3k" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "78179d093acf479be457323548acdf1929a8f538f4d67f575ece725d2b8cb961"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "27aa165a52effe032dce6fd2daa942648a549cd38cb51fb1934cc1d8e5c37e70"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "467f2da506218f25b1ac7fdd392a982634412928a6d872ef9a0a74f53904ec98"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dccdf22bd33c69bf3f66635f17d1d7665f11e670c1fcf68f9d39ba706e858111"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_linux_arm64.tar.gz"
    end
  end

  name "a3k"
  desc "Assessment · Audit · Analyzer for Kubernetes — CLI for cluster analysis and reporting"
  homepage "https://github.com/GustavoEsser/a3k"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a3k"

  # No zap stanza required

end
