# This file was generated by GoReleaser. DO NOT EDIT.
cask "a3k" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "06ce1a2a5746f123ce59deff9e321a0e3ba9596aa6548815072666596a6a0304"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dcafc2fe709d7623e562e427e0eda770f40d280bca5533b24020a80184ce16a1"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "163c53f398e4d2cec99eddc98f9dfffc3efb62f04ea8239422b5f8c7276c2dec"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "27bd6906bceb178f9a1c16689e18177fb047d08a8955f8a6aa5df40bdbcc0c4a"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_linux_arm64.tar.gz"
    end
  end

  name "a3k"
  desc "Assessment · Audit · Analyzer for Kubernetes — CLI for cluster analysis and reporting"
  homepage "https://github.com/GustavoEsser/a3k"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a3k"

  # No zap stanza required

end
