# This file was generated by GoReleaser. DO NOT EDIT.
cask "a3k" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "621d2093b919bdad71eb4c739dff0f14531a089fec37fc0156675ca168d3d0b9"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddeabbcf8a04a4092461abb4e791a518670e0f7dc129f6bd8b8b146cd1f7a515"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0cdc4c91226d340544254807dd2acf66f298df69accb0038bf8e69938176b05"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aeb17cbb3dd73aaaab396c31b91ed90fa538d818014fd63c5bc139b4897813c3"
      url "https://github.com/GustavoEsser/a3k/releases/download/v#{version}/a3k_#{version}_linux_arm64.tar.gz"
    end
  end

  name "a3k"
  desc "Assessment · Audit · Analyzer for Kubernetes — CLI for cluster analysis and reporting"
  homepage "https://github.com/GustavoEsser/a3k"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a3k"

  # No zap stanza required

end
